# Copyright 2018-2021 Volkan Yazıcı
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permits and
# limitations under the License.

name: benchmark

on: [workflow_dispatch]

jobs:

  run:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Maven caching
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Setup JDK 8
        uses: actions/setup-java@v2.3.1
        with:
          distribution: temurin
          java-version: 8
          java-package: jdk
          architecture: x64
          cache: maven

      - name: Build with Maven
        run: ./mvnw -V -B --no-transfer-progress -e -DtrimStackTrace=false verify

      - name: Test scheduler shutdown
        timeout-minutes: 1
        # pwsh (the default shell on Windows) hijacks "exec" keyword
        shell: bash
        run: ./mvnw -V -B --no-transfer-progress -e -DtrimStackTrace=false -Dexec.classpathScope=test -Dexec.mainClass=com.vlkan.rfos.SchedulerShutdownTestApp exec:java

      - name: Run benchmark
        timeout-minutes: 60
        # pwsh (the default shell on Windows) hijacks "exec" keyword
        shell: bash
        run: ./mvnw -V -B --no-transfer-progress -e -DtrimStackTrace=false -Dexec.classpathScope=test -Dexec.mainClass=com.vlkan.rfos.RotatingFileOutputStreamBenchmark -Drfos.benchmark.quick -Drfos.benchmark.concurrency=8 -Drfos.benchmark.jsonOutputFile=benchmarkResult-${{ runner.os }}.json exec:java

      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: benchmarkResult
          path: benchmarkResult-${{ runner.os }}.json
          if-no-files-found: error
